# Generated by Django 3.2 on 2021-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rental', models.IntegerField()),
                ('security', models.IntegerField()),
                ('size', models.CharField(max_length=5)),
                ('productID', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('neck_design', models.CharField(max_length=20)),
                ('sleeves', models.CharField(max_length=20)),
                ('designer', models.CharField(max_length=50)),
            ],
        ),
    ]
